name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.kind }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Setup VS Dev Environment
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64

      - name: Build
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macOS')
        run: |
          mkdir build && cd build
          cmake -G Ninja ..
          cmake --build . -- config Release

      - name: Build (Windows)
        if: startsWith(matrix.os, 'windows')
        run: | 
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=cl.exe -A x64 ..
          cmake --build . -- /property:Configuration=Release

      - name: Release
        uses: justjavac/action-gh-push@v1
        if: |
          startsWith(github.repository, 'justjavac') &&
          github.ref == 'refs/heads/main' &&
          github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        with:
          repository: justjavac/yoga.dll
          files: |
            buck-out/gen/yoga#default,shared/libyogacore.dylib
            buck-out/gen/yoga#default,shared/libyogacore.so
            build/Release/yogacore.dll
